### ISSUE TITLE
How to use AMQP / AMQPS with Spring Cloud Stream Binder Solace

### ISSUE THREAD

**Issue by FWinkler79** [SolaceProducts/spring-cloud-stream-binder-solace#26]
Hi there,

is it possible to use AMQP / AMQPS URIs with Spring Cloud Stream Binder Solace?
I need to connect to a PubSub+ instance exposing only an AMQPS (AMQP over TLS) URI, and I just cannot get it to work with an `application.yml` like this:

```yaml
[...]

solace:
  java:
    host: amqps://localhost:5671  # also does not work for amqp://localhost:5671
    clientUsername: admin
    clientPassword: admin
```
The only thing that seems to work are `tcp://` URIs, but then the binder always uses SMF, not AMQP.
I am confused, since [this](http://solace.com/wp-content/uploads/2018/09/Spring-Cloud-Stream-Binder-datasheet-US_092018.pdf) says it should work, but looking at the latest code, I don't think it's possible.
